name = "mcp-prompt-server"
main = "dist/cloudflare-worker.js"
compatibility_date = "2023-10-30"

# 开发环境配置
[dev]
port = 8787
local = true

# 构建配置
[build]
command = "npm run build:worker"

# KV 命名空间配置
[[kv_namespaces]]
binding = "PROMPTS_KV"
id = "your-kv-namespace-id-here" # 部署时需要替换为实际的 KV 命名空间 ID
preview_id = "your-preview-kv-namespace-id-here" # 本地开发时使用的预览 KV 命名空间 ID

# 环境变量
[vars]
ENVIRONMENT = "production"

# 路由配置
[routes]
pattern = "api.example.com/mcp-prompt-server*"
zone_name = "example.com"

# 触发器配置
[triggers]
crons = ["0 0 * * *"] # 每天凌晨触发一次
