name = "mcp-prompt-server"
main = "dist/workers.js"
compatibility_date = "2023-10-30"

# 开发环境配置
[dev]
port = 8787

# KV 命名空间配置
[[kv_namespaces]]
binding = "PROMPTS_KV"
id = "your-kv-namespace-id-here" # 部署时需要替换为实际的 KV 命名空间 ID
preview_id = "your-preview-kv-namespace-id-here" # 本地开发时使用的预览 KV 命名空间 ID
